version: "3.9"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/dbname
    depends_on:
      - db
    volumes:
      - pythonProject:/home/nya/PycharmProjects/pythonProject

volumes:
  db_data:
  pythonProject:

networks:
  my_network:
    name: my_network
    external: true